### ISSUE TITLE
Push release 1.4.3 to upstream projects

### ISSUE THREAD

**Issue by h3xstream** [h3xstream/find-sec-bugs#101]
I need to update or notify the following projects.
 - [x] Jenkins [jenkinsci/findbugs-plugin #10](https://github.com/jenkinsci/findbugs-plugin/pull/10)
 - [x] SonarQube ([SonarSource/sonar-findbugs #11](https://github.com/SonarSource/sonar-findbugs/pull/11))
 - [x] IntelliJ ([andrepdo/findbugs-idea #107](https://github.com/andrepdo/findbugs-idea/issues/107))
 - [x] Benchmark ([OWASP/Benchmark #12](https://github.com/OWASP/Benchmark/pull/12))
