### ISSUE TITLE
Improvements for JSP support

### ISSUE THREAD

**Issue by h3xstream** [h3xstream/find-sec-bugs#110]
This ticket will regroup the modification related to the JSP improvement of 1.4.4

- [x] Make test assertion on JSP line rather than generated Java source.
- [x] Update the Jetty JSP compiler (partial)
- [x] New rule : Detect dynamic JSP Includes #104 
- [x] New Rule : Detect Spring Eval JSP taglib #55
- [x] New Rule : JSTL out escapeXml=false #114

**Comment by h3xstream** [comment]
The rules set are complete.

Side note: Currently their are contribution being made to Sonar to support the mapping of JSP. Enhancement to the IntelliJ plugin are also planned.
